{% set name = "napari-timeseries-opener-plugin" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-timeseries-opener-plugin-{{ version }}.tar.gz
  sha256: f0cecf5c30b4d57ee3129673ae4718d616b1031de83f42ebbb47a1a62ea8b1ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7
    - qtpy

test:
  imports:
    - napari_timeseries_opener_plugin
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gatoniel/napari-timeseries-opener-plugin
  summary: Simple plugin that opens separate .tif files as a 3-dimensional layer.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
